language: node_js
node_js:
- '4.0'
- '7.0'
os:
- linux
dist: trusty
script:
- bash <(curl -s https://raw.githubusercontent.com/wooorm/atom-travis/master/install.sh)
- export DISPLAY=":99"
- apm rebuild
- npm test
