language: node_js
node_js:
- lts/boron
- node
os:
- linux
dist: trusty
# Needed to disable the auto-install step running `npm install`
install: true
script:
- bash <(curl -s https://raw.githubusercontent.com/wooorm/atom-travis/master/install.sh)
- export DISPLAY=":99"
- apm install
- npm run test-api
