language: node_js
node_js:
  - lts/dubnium
  - node
os: linux
dist: trusty
install: true
script:
  - bash <(curl -s https://raw.githubusercontent.com/wooorm/atom-travis/main/install.sh)
  - export DISPLAY=":99"
  - apm install
  - npm run test-api
